name: Deploy Frontend

on:
  push:
    branches:
      - deploy 
    #   branch yang sedang berjalan sekarang

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: 103.186.0.158
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          bash /var/www/deploy_frontend.sh
